datasets:
  cpi_prediction: # name of the dataset builder
    data_type: videos 
    build_info:
      train:
        url: part.parquet
      val: 
        url: part.parquet
      test:
        url: part.parquet
      use_neg: add_neg0
